import type { NextPage } from 'next'
import { ChangeEvent, MouseEventHandler, useState } from 'react'
import postRequest from '../lib/Request'
import axisBase from 'axios';
import { TextField, Button } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [inputName, setName] = useState('')

  const axios = axisBase.create({
    baseURL: 'http://localhost:3000/portfolio',
    headers: {
      'content-type': 'application/json'
    },
    responseType: 'json'
  })

  const submit = (event: MouseEventHandler | any) => {
    event.preventDefault()
  }

  console.log(inputName)

  axios.post(postRequest.InsertPortfolioData, {
    name: inputName
  })

  const onChangeValue = (event: ChangeEvent<HTMLInputElement>) => {
    event.preventDefault();
    setName(event.target.value);  // 値をStateへセットする
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          <TextField
            value={inputName}
            onChange={onChangeValue}
          />

          <button onClick={submit}>ポートフォリオを作成</button>
        </>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
